-- stg_market_data.sql
-- Cleans Realtor.com-schema market indicators (metro x month grain).
-- Source: Realtor.com Economic Research public data files (attribution required),
-- or the synthetic substitute generated by src/ingest_realtor_data.py in this environment.
CREATE TABLE IF NOT EXISTS stg_market_monthly AS
SELECT
    metro_id,
    metro_name,
    DATE(month)                          AS month,
    CAST(median_listing_price AS REAL)   AS median_listing_price,
    CAST(active_listing_count AS INTEGER) AS active_listing_count,
    CAST(new_listing_count AS INTEGER)   AS new_listing_count,
    CAST(median_days_on_market AS REAL)  AS median_days_on_market,
    CAST(demand_score AS REAL)           AS demand_score,
    CAST(supply_score AS REAL)           AS supply_score,
    CAST(hotness_score AS REAL)          AS hotness_score,
    -- month-over-month and year-over-year price change
    (median_listing_price - LAG(median_listing_price) OVER (PARTITION BY metro_id ORDER BY month))
        / NULLIF(LAG(median_listing_price) OVER (PARTITION BY metro_id ORDER BY month), 0)  AS price_mom_pct,
    (median_listing_price - LAG(median_listing_price, 12) OVER (PARTITION BY metro_id ORDER BY month))
        / NULLIF(LAG(median_listing_price, 12) OVER (PARTITION BY metro_id ORDER BY month), 0) AS price_yoy_pct
FROM raw_market_monthly;
